name: Production Build and Deploy
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
env:
  URL: openq.dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: gh-pages
      url: https://${{ env.URL }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'
      
      - name: Build
        run: |
          cd build
          yarn
          yarn generate
          cd ..
      
      - name: Checkout Repo (gh-pages branch)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          path: 'deploy'
          ref: 'gh-pages'
      
      - name: Push files to gh-pages branch
        run: |
          cp -r build/dist/* deploy
          cd deploy
          touch .nojekyll
          echo ${{ env.URL }} > CNAME
          git add .
          git commit -m $GITHUB_SHA
          git branch -M gh-pages
          git push -u origin gh-pages
